### ISSUE TITLE
`after` key can't guarantee the loading order of plugins if also specifing autocommand `event`

### ISSUE THREAD

**Issue by younger-1** [wbthomason/packer.nvim#1037]
- `nvim --version`: v0.7.2
- `git --version`: 2.37.1
- Operating system/version: Arch Linux/ Kernel 5.10.102.1

### Steps to reproduce

When use `after` key together with `event` key like this one:

```lua
    use {
      'mfussenegger/nvim-dap',
      module = 'dap',
    }
    use {
      'rcarriga/nvim-dap-ui',
      event = 'BufRead',
      after = 'nvim-dap',
    }
  ```
### Actual behaviour
`nvim-dap-ui` will be loaded before `nvim-dap`
![图片](https://user-images.githubusercontent.com/45989017/187478819-977de340-a3bd-4d48-aef1-0efdfd41d203.png)

### Expected behaviour
the plugin `nvim-dap-ui` will only be loaded after the plugin `nvim-dap` loaded
![图片](https://user-images.githubusercontent.com/45989017/187479527-40726cf5-36be-4cb8-b482-9fa16bb28a53.png)

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by EdenEast** [comment]
The keys `event` and `after` both deal with when a plugin is loaded by packer. For the ui plugin spec you are saying that you want to load 'ui' either on `BufRead` events **or** after `dap` is loaded. `after` tells packer that something should be loaded **after** another plugin is loaded. This dose not say that when `ui` is loaded that it should also load `dap`. This would be `requires`. 

`dap` will only be loaded when `require('dap')` is called (because the `module` key is used).

Hope that clarifies it.

**Comment by younger-1** [comment]
Thanks your explanation~
