### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by notwidow** [wbthomason/packer.nvim#1086]
Hi, I have 15 plugins installed and listed by packer also. But when doing packersync or packer update it sometimes shows 17 plugins and sometimes 16 while plugins specified are 15. why is this so?

**Comment by nat-418** [comment]
Please provide steps to reproduce this behavior including a minimal Neovim configuration.

**Comment by notwidow** [comment]
> Please provide steps to reproduce this behavior including a minimal Neovim configuration.

well, first count how many plugins you used and specified in packer.nvim and then run a packersync.. while syncing look at how many plugins it is downloading...it must be 1 or 2 higher than the specified plugins...so why is it showing 1 or 2 more...

**Comment by nat-418** [comment]
I tested with an empty init.lua except for this packer code:

```
return require('packer').startup(function(use)
  use('https://github.com/wbthomason/packer.nvim')
end)
```

snyc says 3 plugins, status says 1

**Comment by notwidow** [comment]
Hey when will it be fixed?

**Comment by nat-418** [comment]
whenever they accept my PR. I don't know how actively packer is maintained

**Comment by notwidow** [comment]
> whenever they accept my PR. I don't know how actively packer is maintained

yeah. i see my fav plugin manager's developers are not that active...

**Comment by wbthomason** [comment]
Yes, my time is very limited. Most work right now is focused on a rewrite of `packer` to fix some long-standing issues and make maintenance easier, which will mean that I can get to more issues, etc. I'm trying to make incremental quality-of-life fixes where I can in the meanwhile. Sorry that this issue has taken so long.

@nat-418: Thanks for the PR! I've played around with it, and I think that changing the constant offset isn't quite right - the extra "plugins" are displayed because we're actually printing the length of the task list, which isn't 1-to-1 with the number of plugins. I think the better fix might be to change the headline text to be "completing N / M {task type: install, update, sync} tasks". Would that be a satisfactory fix?

**Comment by wbthomason** [comment]
(also @notwidow for your opinion on my proposed fix)

**Comment by nat-418** [comment]
Thanks for making Packer and for the explanation. Your solution sounds good to me.

**Comment by wbthomason** [comment]
Yup, understood! Sorry if I came across as angry. Check #1190 out if you get a chance; I'll merge shortly if there are no complaints, as it's a pretty trivial change.
