### ISSUE TITLE
Why `signcolumn=yes:2`?

### ISSUE THREAD

**Issue by runiq** [wbthomason/packer.nvim#11]
Just wondering: What is the point of `signcolumn=yes:2` in the packer.nvim window? I haven't ever seen any output in there…

**Comment by wbthomason** [comment]
Totally reasonable question - I think that was left over from an earlier version of the `display` module in which I was using signs to show operation status rather than writing symbols directly in the buffer.

I've changed this in 8a6e3b0; please let me know if you notice any regressions due to the change!

**Comment by runiq** [comment]
Ah, I totally missed the comment where it said it was adapted from vim-packager.

Thanks! :)

**Comment by wbthomason** [comment]
Yup, though I kept it around for the aforementioned sign-based display (ended up not sticking with that route because it was slightly more complicated for no clear gain).
