### ISSUE TITLE
Packer.nvim washes out screen when using a disabled colorscheme

### ISSUE THREAD

**Issue by sidmadala** [wbthomason/packer.nvim#124]
- `nvim --version`: NVIM v0.5.0-dev+4383c0f
- packer.nvim version(commit hash): ccfb54cebc6cf0e717ce4391b377afc43897d504
- `:checkhealth` result: All green
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Use the configuration I have pasted below.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

-- Automatically compile lazy loaders
vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

	-- Aesthetic
	use {"jnurmine/zenburn", config = 'require("plugins.colorscheme")'}
	use {"aonemd/kuroi.vim", config = 'require("plugins.colorscheme")', disable = true}

end)
```
</details>

<details>
<summary>colorscheme.lua</summary>

```lua
--[[
Colorscheme Configuration
--]]

vim.cmd [[ colorscheme zenburn ]]
vim.g.zenburn_high_Contrast = 1
```
</details>

### Actual behaviour

Vim looks washed out with a low contrast background when using 'require(plugins.colorscheme)' for the disabled theme. When the outside quotes are removed, the background is normal. Refer to the photos below.

<img width="1424" alt="Screen Shot 2020-12-18 at 12 01 01 AM" src="https://user-images.githubusercontent.com/22417141/102576752-5f34de00-40c4-11eb-8266-e3669137fd1c.png">

<img width="1430" alt="Screen Shot 2020-12-18 at 12 01 19 AM" src="https://user-images.githubusercontent.com/22417141/102576757-6360fb80-40c4-11eb-8420-0a17d6f56ea8.png">

### Expected behaviour

I would expect that Packer.nvim lets Neovim use the high contrast background all the time by completely ignoring the disabled theme/plugin line.

**Comment by wbthomason** [comment]
Did you run `PackerSync` after disabling the colorscheme?

**Comment by sidmadala** [comment]
Yes, I ran `PackerSync` after disabling the theme. I think that at least one of the `require` statements cannot be surrounded by quotes. However, I do not know the reason why.

**Comment by wbthomason** [comment]
Forgive me if I am mistaken, but it appears that the two `require` statements are for the same file? I'm not sure why you would see any different effect.

Do you see two lines in your `packer_compiled.vim` that say `require('colorscheme')`? That would indicate a bug with the compile module not ignoring disabled plugins.

**Comment by sidmadala** [comment]
I manage my colorschemes in one file, hence the same filename. I do not have any calls to the disabled theme though. There is only one `require("plugins.colorscheme")` in `packer_compiled.vim`.

**Comment by wbthomason** [comment]
Ok. I'm pretty sure I know what's happening here, after looking through your dotfiles more.

This actually doesn't have to do with the `disabled` colorscheme or a `packer` bug, as far as I can tell. The problem is that, in your `colorscheme.lua`. you're setting the high contrast variable **after** you use the `colorscheme` command to set `zenburn` as your colorscheme. Thus, the "washed out" screen is just what Zenburn looks like without the high contrast background.

Additionally, the problem you have with removing the quotes is because (as mentioned in #114), your `colorscheme.lua` file does not return a function, so the value of the `require` call cannot be compiled into the lazy loaders. If you used the following:

```lua
return function()
  vim.g.zenburn_high_Contrast = 1
  vim.cmd [[ colorscheme zenburn ]]
end
```
in your `colorscheme.lua`, things should work as expected.

I suspect that you were getting the dark background in this case because of some quirk that resulted in the high contrast variable being set before you ran `colorscheme`, though I'm not sure specifically how (I was able to reproduce everything except for that).

**Comment by sidmadala** [comment]
Switching the two lines fixed the issue. That seems really weird. Thank you for your help.

**Comment by wbthomason** [comment]
Yep. It's actually not unexpected - when you run `colorscheme`, it just sources the file in `<zenburn clone location>/colors/zenburn.vim`. So, if you don't have the global variable indicating that you want high contrast set before you run `colorscheme`, `zenburn.vim` will use a default value, which happens to not be high contrast.
