### ISSUE TITLE
Embeded functions in config is not working

### ISSUE THREAD

**Issue by tramhao** [wbthomason/packer.nvim#148]
I load wiki.vim and it works, but the below code chunk for MyFunction is not working:

```
    use {'lervag/wiki.vim', 
    config = function ()
            vim.g.wiki_root = "~/Sync/wiki"
            vim.g.wiki_filetypes = {"md"}
            vim.g.wiki_write_on_nav = 1
            vim.api.nvim_exec(
            [[
            
            function MyFunction(text) abort
               return substitute(tolower(a:text), '\s\+', '-', 'g')
            endfunction

            let g:wiki_map_link_create = 'MyFunction'
            ]],
            false)
           end,
    -- ft = 'markdown',
        }

```
It compiles with no error, but when I create links, the text is not modified.

**Comment by akinsho** [comment]
@tramhao have you run `PackerCompile` you will also need to restart neovim. I was going to raise an issue around using function or require configs they, are a little tricky since you
1. can't use any local variables
2. you have to run packer compile and reset neovim whenever you add and change one
3. sometimes you have to delete the `packer_compiled.vim` to get them to regenerate, this is usually if there is an error in what was compiled

**Comment by tramhao** [comment]
I have recompile it and checked the compiled file, there are some lines with wired string codes and my function name in it. About local variable, you mean all the variable used must be global? Maybe this is the problem. In such situation, should I use lua for the calculation and not nvim_exec? Thanks.

**Comment by akinsho** [comment]
@tramhao sorry that wasn't super clear I mean
```lua
local an_alias = vim.fn
use {"my-plugin", config = function()
   an_alias.has('feature') -- use of local variable here will fail
end}
```
Regarding the appearance of the compiled file hard to say since it generally produces an unintelligible string so could be working or not. Tbh I can't see anything wrong in the code you shared.

I just know from my own experiences that there tends to be a bit of a dance with config functions i.e. is the packer compiled file up to date and picking up your function (maybe you can search for a matching word in the compiled output), have you reset neovim etc.

**Comment by tramhao** [comment]
I just got back my laptop so here is the related lines in the compiled file:
```
 -- Config for: wiki.vim
  1 loadstring("\27LJ\1\2ò\2\0\0\3\0\n\0\0194\0\0\0007\0\1\0%\1\3\0:\1\2\    0004\0\0\0007\0\1\0003\1\5\0:\1\4\0004\0\0\0007\0\1\0'\1\1\0:\1\6\000    4\0\0\0007\0\a\0007\0\b\0%\1\t\0)\2\1\0>\0\3\1G\0\1\0Ð\1            f    unction MyFunction(text) abort\n               return substitute(tolo    wer(a:text), '\\s\\+', '-', 'g')\n            endfunction\n\n
        let g:wiki_map_link_create = 'MyFunction'\n            \14nvim_ex    ec\bapi\22wiki_write_on_nav\1\2\0\0\amd\19wiki_filetypes\16~/Sync/wik    i\14wiki_root\6g\bvim\0")()
```

I think it's compiled in it. Meanwhile, I asked the same question to the author or wiki.vim, but he's not familiar with lua, and are not using packer.nvim, so he cannot help with this issue. The link is here:
https://github.com/lervag/wiki.vim/issues/127

But don't worry. Probably I could figure out another way to get around it. Thanks.

**Comment by wbthomason** [comment]
@tramhao Thanks for the report! Your config looks fine at a glance. I'm actually not able to reproduce your issue - when I use your config snippet, `MyFunction` exists and is callable, and is called when I create a link (e.g. pressing `<cr>` with `foo bar` visually selected results in `[[foo-bar|foo bar]]`).

Could you give an example where this does not work as expected?

**Comment by tramhao** [comment]
My fault! It's working and thanks! 
I repeated on the wrong text. The code is fine.

**Comment by tramhao** [comment]
after some upgrade(latest master I'm on), the code above will return error during compile with messages below:
```
Error in packer_compiled: Vim(lua):E5108: Error executing lua [string ":l
ua"]:15: [string "..."]:0: Vim(function):E122: Function MyFunction3 alrea
dy exists, add ! to replace it
Please check your config for correctness
```

**Comment by tramhao** [comment]
It's working if I change the name of function to a new one.

**Comment by akinsho** [comment]
@tramhao this is an issue with how vimscript works and not really related to `packer` in vimscript you should define your function like
```vim
" NOTE: the ! after function
function! MyFunction()
" stuff here
endfunction
```
The `!` after the function keyword tells vim to replace the function if it is redeclared. In this case when you run packer compile in a running vim instance it re-runs your config in case it changed and so will try and re-define this function which is fine normally especially if you changed the function but in your case because there is no `!` the function can't be redefined

**Comment by tramhao** [comment]
You saved my day! It's working great!

**Comment by wbthomason** [comment]
Thanks, @akinsho!
