### ISSUE TITLE
log.lua:113: attempt to index local 'fp' (a nil value)

### ISSUE THREAD

**Issue by thorlucas** [wbthomason/packer.nvim#199]
After adding

```lua
use {
	'nvim-telescope/telescope.nvim',
	opt = true,
	requires = {
		{ 'nvim-lua/popup.nvim', opt = true },
		{ 'nvim-lua/plenary.nvim', opt = true }
	}
}
```

to my packer file and 

```lua
vim.cmd [[packadd plenary.nvim]]
vim.cmd [[packadd popup.nvim]]
vim.cmd [[packadd telescope.nvim]]
```

to my plugin file, every time I run `:PackerUpdate`, we get:

```
Error executing vim.schedule lua callback: ...nvim/site/pack/packer/opt/packer.nvim/lua/packer/log.lua:113: attempt to index local 'fp' (a nil value)
```

This also seems to have permanently broken something because my packer is throwing these errors even after commenting out these lines.

**Comment by wbthomason** [comment]
Thanks for this report! What OS are you on? This error points to a failure to open the file `packer` outputs log messages to, which is a strange failure.

**Comment by kkga** [comment]
Getting the same exact error, macOS 11.2.

**Comment by wbthomason** [comment]
Could you tell me (1) what `lua string.format('%s/%s.log', vim.fn.stdpath('cache'), 'packer.nvim')` returns for you and (2) if there is a file at that location?

The lines where this error is occurring try to open this file (with normal `io.open`), then write the log output to it. So, this error means `io.open` is failing, which usually means a permissions or path issue is present.

I've also added (in the latest commit, f4b0361) a print message for any error message that occurs when `io.open` fails. If you see this (might be in `:messages`), please post it here. Thanks!

**Comment by thorlucas** [comment]
> Could you tell me (1) what lua string.format('%s/%s.log', vim.fn.stdpath('cache'), 'packer.nvim') returns for you

```
/Users/thorcorreia/.cache/nvim/packer.nvim.log

-> cat /Users/thorcorreia/.cache/nvim/packer.nvim.log
cat: /Users/thorcorreia/.cache/nvim/packer.nvim.log: No such file or directory
``` 

It seems there exists no directory `nvim` in `~/.cache`. Running `mkdir` seems to have fixed that.

Perhaps the io command should check that this directory exists?

**Comment by wbthomason** [comment]
Yep, it absolutely should. This is the first time I've seen that directory not exist (I actually thought that Neovim always already created it for us, as it's a standard data directory), but I'll add a check. Thanks for your help!

**Comment by klooj** [comment]
FYI, I still  get this error sporadically but I didn't open a new issue because I cannot reproduce on demand.  I'll debug it further whenever it happens next. But here are some details in case something obvious jumps out to you:

1. The fix from above does not apply because I catted the file at  lua string.format('%s/%s.log', vim.fn.stdpath('cache'), 'packer.nvim') to generate the image below:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/57016271/111577607-fd4e4800-8788-11eb-8839-22b354e66629.png">

2. It only happens on macOS and I'm pretty sure it has only happened on the macbook, not the mini. But both machines have the same version of BigSur and run identical nvim configs---nightly build + [my config](https://github.com/klooj/nvimrc-lua). Linux machines do not seem to have an issue.

**Comment by wbthomason** [comment]
@klooj: Thanks, I'm adding another check that `fp` is non-nil in this new location.
