### ISSUE TITLE
can not install nvim-compe

### ISSUE THREAD

**Issue by matu3ba** [wbthomason/packer.nvim#208]
`  --use { 'hrsh7th/nvim-compe', requires = { 'norcalli/snippets.nvim' } }`

Can you reproduce?

**Comment by matu3ba** [comment]
It fetches something and does something, but then just immediately shows the following status message:

 ✗ Failed to install hrsh7th/nvim-compe
  Commits:
    bef454e Remove `menu` from `completeopt` suggestions (#164) (vor 9 Stunden)

Is there a log file for packer to look things up?

**Comment by akinsho** [comment]
@matu3ba there is but I'm not 100% sure of it's location, maybe somewhere in the `stdpath('log')` directory. The error on startup is just because it can't find `compe` I believe. Regarding the error you see on install, you can press enter on the line that errored and I think `packer` will show you some more information on why it failed, that might give some more clues

**Comment by matu3ba** [comment]
@wbthomason Can you set a FAQ/wiki with quick instructions how to delete and reinstall packer?

For whatever reasons, it works again now.

**Comment by wbthomason** [comment]
The log is at `~/.cache/nvim/packer.nvim.log`; that location should be better advertised. Sorry for the hassle - if it happens again, or if I/someone else can reproduce it, please feel free to re-open this issue.
