### ISSUE TITLE
Plugins to be deleted appear as failed updates running PackerSync

### ISSUE THREAD

**Issue by akinsho** [wbthomason/packer.nvim#209]
When running `PackerSync` and some plugins are due to be removed they also appear as failed updates. My guess would be that things are happening out of order somewhere i.e. if packages are due to be removed they should not being counted as things to update so should not then show an update failure message

![image](https://user-images.githubusercontent.com/22454918/107687623-a0013b80-6c9e-11eb-9b1f-996bafab976e.png)

**Comment by wbthomason** [comment]
Thanks! This feels probably related to #157? I haven't been able to reproduce this yet, but I suspect that this might be caused by needing to filter out plugins which will be cleaned from the update set.

That said...plugins being removed presumably do not appear in the plugin specification file (or are disabled), and these should **already** not be updated.

Out of curiosity, what actions did you take that resulted in this (i.e. did you disable plugins or delete specifications)?

**Comment by akinsho** [comment]
@wbthomason I've seen this in a few different situations sporadically but my setup is definitely a little complex. In this particular situation I was essentially testing the behaviour of a `disable` variable. I had a few plugins installed that I changed the `disable` value of from `false` to `true`, so I think they would have originally been flagged as being for updating but actually had just shifted to being for deletion.

I just tested it locally and it took a bit of fiddling but I was able to reproduce it by toggling the status of the disabled field after rejecting deleting the plugin after the prompt then running packer sync again

**Comment by wbthomason** [comment]
If I'm understanding your repro example correctly (haven't had a chance to test it myself yet), it sounds like this may have something to do with the plugin specification not being properly reloaded? Though I am not sure why the disabled state would persist across runs to cause the plugins to be both on the remove and update lists.

**Comment by wbthomason** [comment]
Obvious in retrospect: `update` should never be applied to disabled plugins.
