### ISSUE TITLE
 Directory not found in 'packpath': "pack/*/opt/packer.nvim"

### ISSUE THREAD

**Issue by teto** [wbthomason/packer.nvim#235]
I have packer (from master) up and working yet on startup I get
```
config/nvim/plugin/packer_compiled.vim|10| 
|| E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
```
This may be triggered by the fact that `~/.config/nvim/init.vim` is a symlink to another folder `~/home/config/nvim`. Any tip on how to fix this ?

**Comment by clason** [comment]
But it works in `start`, right? Did you `packadd` the packer directory manually?

**Comment by wantyapps** [comment]
I think this is the pack path is the problem in #233

**Comment by teto** [comment]
I have packer install in `start`. I've tried some things but it fails with 
```
async.lua:17: Error in coroutine: ...k-dir/pack/home-manager/start/packer-nvim/lua/packer.lua:316: attempt to index local 'display_win' (a nil value)
```
seems like this function doesnt return a display_win when update_plugins == {}
```
local function do_update(_, plugins, update_plugins, display_win, results)
  results = results or {}
  results.updates = results.updates or {}
  results.plugins = results.plugins or {}
  local tasks = {}
  for _, v in ipairs(update_plugins) do
    local plugin = plugins[v]
    if not plugin.frozen then
      if display_win == nil then
        display_win = display.open(config.display.open_fn or config.display.open_cmd)
      end

      table.insert(tasks, update_plugin(plugin, display_win, results))
    end
  end

  if #tasks == 0 then log.info('Nothing to update!') end

  return tasks, display_win
end
```

**Comment by teto** [comment]
Do we really need the `packadd packer.nvim` in `config/nvim/plugin/packer_compiled.vim` ?
Admittedly I have a fairly complex neovim setup (with plugins installed via nix/vim-plug and packer :s ) but this failed twice for me:
First because I install packer via nix and nix renamed the directory in pack/ from packer.nvim to packer-nvim (bad nix !).
As a fallback I tried to install packer via vim-plug and so it was available but not in packpath.

I had to fork the project to ease debugging because messages are not informative enough. For instance I had `All configured plugins are installed` for a moment but I I was not sure wether it was detecting my plugins or not (in fact, I had forgotten to restore my packer config so it was actually trying to install 0 plugin, my bad). Some sporadic `log.debug` could be helpful :)

**Comment by wbthomason** [comment]
Thanks for the report!

> seems like this function doesnt return a display_win when update_plugins == {}

This seems like a different issue, could you please open one?

> Do we really need the packadd packer.nvim in config/nvim/plugin/packer_compiled.vim ?

That's there (1) in case users have `packer` installed as `opt` and (2) because it should be a null-op if they don't or have it already loaded. I'm guessing that your trouble with it arises because you're not using `packer` to manage itself, and are just using it for `luarocks` support? Given that we want to support this use case, maybe we should either clarify that using the `luarocks` features without managing plugins via `packer` is best done manually with the functions `luarocks` provides rather than using `PackerSync`, or add a config var to disable `packadd`ing and `require`ing `packer` in the compiled file.

> Some sporadic log.debug could be helpful :)

Agreed! If you have suggestions for where, based on your debugging, I'd be happy to merge a PR. I've been gradually adding more/better logging as I fix things, but I've been slow about it.

**Comment by teto** [comment]
I've fixed the issue on the nixpkgs side https://github.com/NixOS/nixpkgs/pull/136131, the rest may be irrelevant now.

**Comment by wbthomason** [comment]
Thanks for the update!

**Comment by iFrostizz** [comment]
Same issue on Manjaro :/

**Comment by wbthomason** [comment]
@iFrostizz Please create a new issue with the issue template; this issue is old enough that I don't think we'll be able to debug your problem from its state.
