### ISSUE TITLE
How to manage a dependency between two lazy load plugins?

### ISSUE THREAD

**Issue by weilbith** [wbthomason/packer.nvim#250]
Hey,
I have the following concrete example:

```vim
lua packer.use({
      \   'nvim-telescope/telescope.nvim',
      \   requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}, {'kyazdani42/nvim-web-devicons'}},
      \   cmd = 'Telescope',
      \   config = 'vim.cmd("packadd telescope")',
      \ })
```

and 

```vim
lua packer.use({
      \   'pwntester/octo.nvim',
      \   requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}},
      \   after = 'telescope.nvim',
      \   cmd = 'Octo',
      \   config = 'vim.cmd("packadd octo")',
      \ })
```

These `opt` packages I load in the `config` properties are just my way of loading plugin configuration. These packages just include all the setup calls, setting variables, highlights, signs, custom functions etc. pp.

The problem now is that both of these plugins get lazy loaded. But the `octo.nvim` plugin requires the `telescope.nvim` one. My approach to resolve this is with the `after` property.Telescope by itself just works fine. But Octo does not work until I load Telescope somehow else (i.e. run as `:Telescope...` command, cancel it, and then call `:Octo...`).
How can I resolve this issue to make it just work?

EDIT: Back then I tried to add `telescope.nvim` to the `require` list of Octo. But that gave me errors by Packer.

**Comment by wbthomason** [comment]
Thanks for the report and example! I think this may be somewhere that `packer`'s sequenced loading needs to be improved...there's a way to hack this right now, but it's pretty gross. I think what we'd want is a `before` key or similar, so that you could trigger `telescope` to be loaded whenever `octo` is loaded (or the long-outstanding improvements to `requires` mentioned in #87).

The issue right now is that - while `octo` will be loaded whenever `telescope` is - there's nothing specifying that `telescope` should be loaded *before* `octo` is loaded. You could hack this by lazy-loading `telescope` on the `Octo` command (and keeping the `after = 'telescope.nvim' for `octo`), but that is inelegant and requires too much manual specification.

**Comment by weilbith** [comment]
Sorry for the late response. :expressionless: 

So is there already an open issue for the `before` behavior? I thought to remember of an issue where this was part of the conversation. But by a quick search I can't find it again. If it exists, I assume we can close this issue here?

**Comment by weilbith** [comment]
So as there is already #87 should we just close this issue here? Or is the `before` behavior a new issue by itself?

PS: Sorry for the belated response. :expressionless:

**Comment by weilbith** [comment]
I have the same problem with `ultest` and `vim-test` now...

**Comment by wbthomason** [comment]
Sorry, I haven't had time to implement `before`, and likely won't very soon. If you'd like to take a stab at it, I'd be happy to provide guidance - the main change this would require is modifying the topological sort and associated sequence list building in `compile.lua` and `load.lua` to create and handle a "before" load list paralleling the existing "after" load list. This would also clear the path for #87 finally being resolved.

**Comment by weilbith** [comment]
Haha, I just opened the PR already before/while you added the comment. Haven't seen it then. But it should kinda align with what you have written. Looking forward to get feedback.
