### ISSUE TITLE
Don't load on certain filetypes

### ISSUE THREAD

**Issue by AckslD** [wbthomason/packer.nvim#257]
`ft` can be used to load a plugin on certain filetypes. Is there a way to instead specify that a plugin should always be loaded except on certain filetypes?

**Comment by akinsho** [comment]
@AckslD how would that work? since loading a plugin is a one time thing is the idea that if you open neovim it won't load if the filetype is the one you want to avoid it on otherwise it always loads? Out of interest whats the actual problem you are trying to solve there might be another way to do this already in packer?

Seems like this would only be useful if you sometimes opened vim on certain filetypes and didn't want a plugin loaded if you opened nvim on it but tbh the moment you go into another file it will load the plugin anyway right?

**Comment by AckslD** [comment]
@akinsho Thanks for your reply! I think I missunderstood what `ft` does, didn't completely think it through. Didn't realise that the plugin stays loaded even if you go to another filetype.

I'm using `vim-rainbow` but I don't want it to load in e.g. python files. But I guess the better way is to use autocommands.

**Comment by akinsho** [comment]
rainbow can also be configured to work only in certain filetypes in it's config I believe
I use `luochen1990/rainbow` like
```lua
    use {
      "luochen1990/rainbow",
      config = function()
        vim.g.rainbow_active = 1
        -- enable only for dart
        vim.g.rainbow_conf = {
          separately = {
            ["*"] = 0,
            dart = {
              operators = "",
              parentheses = {[[start=/(/ end=/)/ fold]], [[start=/\[/ end=/\]/ fold]]}
            }
          }
        }
      end
    }
```
I'm guessing vim rainbow does something similar i.e. a way to only apply to certain filetypes
Also worth noting #32 exists which I think is a similar request

**Comment by AckslD** [comment]
Thanks for sharing @akinsho, it indeed looks like you can disable a filetype directly in the config :+1:.
