### ISSUE TITLE
:Packercompile code execution issue

### ISSUE THREAD

**Issue by hoob3rt** [wbthomason/packer.nvim#266]
Currently setting the colorscheme in a file cotaining packer's setup function breaks other lua plugins which use `vim.api` to pull highlight colors.

See more details [here](https://github.com/hoob3rt/lualine.nvim/issues/143)

```lua
require("packer").startup {
  function()
    use "wbthomason/packer.nvim"
    use {
      "gruvbox-community/gruvbox",
      -- this code should probably execute before the "lua plugin" config
      config = function()
        vim.cmd("colorscheme gruvbox")
      end
    }
    use {
      "lua plugin",
      config = function()
        -- ...
      end
    }
   
  end
}
```

**Comment by akinsho** [comment]
@hoob3rt in the example above the theoretical lua plugin can be setup before or after gruvbox I think maybe the misunderstanding is that because gruvbox is declared first it will load first but packer doesn't guarantee ordering in that way (@wbthomason can correct me if I'm wrong)

If someone wants to ensure that one plugin is loaded before the other then in this example the theoretical `lua plugin` should specify and `after = "gruvbox"` but since it's a colorscheme I think it's best to just run the `colorscheme <value>` command in the users `init.lua` rather than in the `config` key of the colorscheme plugin

**Comment by wbthomason** [comment]
@akinsho is correct; the way to ensure a particular load order is with the `after` key, and it is usually cleanest to just run `colorscheme` in your `init.lua` (which runs before the contents of `packer_compiled` anyway, so your desired sequencing property should be upheld).

I'm closing this because it seems like @akinsho solved your problem, but please feel free to re-open if you're still having issues.
