### ISSUE TITLE
Compared to dein?

### ISSUE THREAD

**Issue by krisfans** [wbthomason/packer.nvim#282]
Hi,  could you briefly compare packer to [dein](https://github.com/Shougo/dein.vim) (if you have experience with it)? Thanks!

**Comment by wbthomason** [comment]
It's been a while since I used `dein`, so this might be out of date, but I'll try:

- `dein` has been around much longer, and @Shougo is a wizard, so I'm sure it has fixed issues that `packer` hasn't, probably has tricks that we don't, etc. 
- Both `packer` and `dein` offer a large number of ways to defer loading plugins - I think the sets of features here are roughly equal, though I haven't done a careful analysis.
- `dein` has some features that `packer` doesn't and won't, like configuring via TOML
- `packer` also has some features that `dein` doesn't, like Luarocks integration and (soon) integrated startup profiling
- `packer` is easiest to use from Lua; `dein` is easiest to use from Vimscript
- `dein` may be compatible with Vim; `packer` is only compatible with Neovim
- `packer` uses native packages (for now); `dein` uses `rtp`-modification
- `packer` loads plugins via a generated file; I think `dein` does something similar but doesn't cache/generate the same set of information
- `packer` has a plugin operation display built in; I don't think `dein` does

Overall, I think `dein` and `packer` have a lot of similarities, but `dein` is absolutely the more mature option. I think `packer`'s strengths (for me) lie in expressivity of configuration, as well as a few features we already have or are working on (e.g. Luarocks, splitting configs across multiple files, profiling, etc.) that are newer. Both are good options, in my opinion, and I hope that `packer` can get to `dein`'s level of polish!
