### ISSUE TITLE
How to use Luarocks and Hererocks within Nvim?

### ISSUE THREAD

**Issue by Pocco81** [wbthomason/packer.nvim#283]
Hello! I'm new to both init.lua and Packer (been using init.lua and Plug my whole life), although I did know Lua and Luarocks beforehand. I just found the luarocks capability of this plugin, but unfortunately I can't figure out how to use it. Currently what I'm trying to achieve is to require a rock from a file that's being sourced from init.lua:

**init.lua**
```lua
require("pluginsList.lua")      -- packer, for installing plugins
require("myTest.lua")            -- the file where the rock is used
```

**pluginList/lua.lua**
```lua
-- check if packer is installed (~/local/share/nvim/site/pack)
local packer_exists = pcall(vim.cmd, [[packadd packer.nvim]])
return require("packer").startup(
    function()

        -- main - puglin manager
        use {"wbthomason/packer.nvim", opt = true}

       -- some plugins here in the middle...

        ----------------------------=== Luarocks ===--------------------------
            use_rocks 'effil'    -- the rock I need
    end
)
```

**myTest/lua.lua**
```lua
local effil = require("effil")
```

The docs say that one should call the function `packer.luarocks.install_commands()` in order to unlock the PackerRock command. And so I did with this line of code `require("packer").luarocks.hererocks_is_setup()` but it's showing this:
![image](https://user-images.githubusercontent.com/58336662/114032164-a98fc580-9841-11eb-8194-3344f4c0344d.png)

Can somebody help me with this and teach me how to go about it? And also, how should I call this library from `myTest/lua.lua`?

**Comment by akinsho** [comment]
@kdav5758 I think you can go about what you want more easily than using the `install_commands` or `is_setup()` function. When you use `use_rocks` that should install the lua rock. Before adding it to some part of your config I would call `PackerInstall` *before* trying to require your rock. So that it can be installed first.

So steps are:
1. add `use_rocks 'effil'`
2. run `PackerSync` this should install the rock, or show you an error
3. easiest to reload nvim at this point
4. check if the rock was installed e.g. `:lua print(vim.inspect(require'effil'))`

Then once it is installed it is safe to use in your config. One thing to clarify is that 
```
require("pluginsList.lua")      -- Plugins have not been loaded at this point
require("myTest.lua")            -- If used here the plugin might not be installed yet on the first run so this will error
```

if you want to specify things int he order you have above I recommend using `pcall` so that the config is more portable

**Comment by kdav5758** [comment]
Thanks for replying @akinsho! Following your recomendations, I replaced all my require calls with `pcalls` like so:

```
-- lua
pcall(require,"pluginsList.lua")      -- packer, for installing plugins
pcall(require,"file-icons.lua")       -- icons, for nvimTree
pcall(require,"misc-utils.lua")       -- general configs
pcall(require,"nvimTree.lua")         -- file explorer
pcall(require,"bufferline.lua")       -- bufferLine, show buffers as tabs
pcall(require,"statusline.lua")       -- galaxyline, a modern status line
pcall(require,"indentBlackLine.lua")  -- manage indentation
pcall(require,"treesitter.lua")       -- treesitter, better syntax highlighting
pcall(require,"cocNvim.lua")          -- coc.nvim, completion, lintings, LSP
pcall(require,"mappings.lua")         -- editor's mappings
pcall(require,"gitsigns.lua")         -- git specific icons
pcall(require,"colorScheme.lua")      -- color scheme and highlights
pcall(require,"colorizer.setup()")     -- colorizer for nvim
```

I also ran :PackerSync after I did the :PackerInstall and I can now require the library, tho I came across some new issues:
1. Running `:lua print(vim.inspect(require'effil'))` gives me this error:
![image](https://user-images.githubusercontent.com/58336662/114068746-d654d480-9863-11eb-8069-0c81afa94dd0.png)
But I can now require the library from pluginList/lua.lua like so without any errors:
```lua
local effil = require("effil")
```
2. I already have `hererocks` installed (w/ `pip3` and `pip`), but while doing `:PackerSync` the "loading" icon never turns into a checkmark in the case of `hererocks`, even after 5-6 minutes:
![image](https://user-images.githubusercontent.com/58336662/114069187-52e7b300-9864-11eb-91c0-fb1b6130fd0c.png)
It never stops...
3. How can I require the library from **myTest/lua.lua**? when I try to require the library outside of **pluginList/lua.lua** it doesn't let me. I guess I'm supposed to do something like `require("packer")` before the `local effil = require("effil")`. Could you also help me with this?


Thanks again for the fast response btw!

**Comment by wbthomason** [comment]
@kdav5758 It looks like your environment might be interfering with what `packer` expects for Luarocks use (which might mean we need to fix something). Specifically, it seems that your rock has been installed to a `luaenv` path for Lua 5.3, whereas `packer` expects to install rocks to its own path, and only works with LuaJIT (so, Lua 5.1 - this restriction is because Neovim uses LuaJIT in most environments).

For the `hererocks` installation hang: can you share (1) the details about your environment and (2) the contents, if any, of `~/.cache/nvim/packer.nvim.log`?

You should be able to `require` the library from anywhere within Neovim (except `init.lua` unless you manually source `packer_compiled` first or set up the modifications to `package.path` and `package.cpath` yourself - this is a known issue).

I think what's happening is that Lua on your system looks in the wrong environment if you try to `require` before `packer_compiled` has been sourced. As a workaround, I'd suggest copying the `package.path` etc. lines from `packer_compiled` to the start of your `init.lua`, and seeing if `require`s work as expected then.

**Comment by akinsho** [comment]
As a side note so they don't remain in you config forever the comment about adding a `pcall(require('thing-uses-effil'))` was just about silencing the error in the one file where you were using the rock that hadn't been installed so it wouldn't error whilst you re-ran packer sync. You shouldn't generally need to wrap all your requires like that

**Comment by wbthomason** [comment]
Fascinating, thanks for the info...

I'm fairly convinced this has to do with your `luaenv` setup, but ideally that should not interfere with Neovim or `packer`. When you say you tried with Lua 5.1 as well, do you mean that you tried using `luaver 5.1` and the same package_path?

Also, could you please try copying the `package.path` modifications from the top of your `packer_compiled`? These should help point Neovim toward `packer`'s `hererocks` installation.

Although I don't think it's the issue here (maybe), we should probably also update `packer` to check for existing system `hererocks` before installing it locally.

**Comment by koopa1338** [comment]
I have a similar issue. I tried to install the penlight lib with packer, which worked as expected but if I try to use it in any lua file I get an error, that the lib is not found. Seems like the package paths don't get setup correctly.

What works as a workaround is copying the `package.path` and `package.cpath` settings from the `packer_compiled.vim` to my `init.lua`
What seems odd to me is, that on startup it can't load it in my lua file, but a `:lua print(vim.inspect(require('pl')))` prints `true` so maybe the `packer_compiled.vim` should be loaded earlier?

**Comment by wbthomason** [comment]
@koopa1338 Yes, it sounds like you're trying to use the rocks before `packer_compiled` is sourced. By default, this happens *after* `init.lua` is sourced (just due to the order in which Neovim loads configuration files). Forthcoming work in #402 should allow installed rocks to be used in `init.lua`.

**Comment by dstadelm** [comment]
I too have the hang issue, when I try to install telescope-arecibo.nvim 

I didn't quite understand from the history here, if there is a solution to this problem.

**Comment by Cassin01** [comment]
Im mac user.

My config worked with this ↓ setting.

```lua
local local_package_path = "./?.lua;/Users/name/.config/nvim/lua5.1/share/lua/5.1/?.lua;/Users/name/.config/nvim/lua5.1/share/lua/5.1/?/init.lua"
package.path = package.path..';'..local_package_path
```
