### ISSUE TITLE
Confusion over pattern in module key of use

### ISSUE THREAD

**Issue by bphilly96** [wbthomason/packer.nvim#293]
When lazy loading a plugin using the module key in use, the docs state the value of module should be a pattern. However in the source code at https://github.com/wbthomason/packer.nvim/blob/fdf1851c6121dee98294791c72aebff92b99b733/lua/packer/compile.lua#L50 the pattern is escaped meaning the pattern will be treated literally. Is this behaviour intended? Shouldn't the user escape the pattern manually so that they can choose which characters to treat literally and which to treat as special characters?

For example is the user wanted to lazy load on any module name consisting of upper-case letters or punctuation they would set `module = '[%u%p]+$'`. The current implementation would escape all of these special characters and cause string.match to treat them literally.

Furthermore, should the leading `"^"` that's in the source code be documented as well as documenting that there is no trailing `"$"` inserted for you? I'm happy to add this myself, just want to make sure I'm not misunderstanding something.

**Comment by akinsho** [comment]
@bphilly96 I think the way it is now is a little messy, when I initially added this functionality my thinking was that this would mainly be used literally i.e. specifying the name `my-plugin.lua`, @wbthomason and I collaborated on the PR and I believe his plan was for it to be a pattern, so it could be used as flexibly as you describe. So the docs as they stand should probably not point towards this taking a pattern, since we escape special characters.

I'd be curious to know what @wbthomason thinks, but I *personally* feel that a lot of people in the nvim community are quite new to lua let alone to lua patterns, by not escaping this/trying to accomodate patterns I feel this makes this feature have quite a high barrier to entry since in order to use it literally i.e. 'please lazy load directly "my-module"' a user would have to understand that they need to escape the pattern.

I think to allow for flexibility it would be nice if there was some way to tell ahead of time if the person means to use a pattern or if they just want to specify the module directly and handle this based on what the value of the key is, but in lieu of that solution/in a bid to do things simply and accessibly I think just specifying a module plainly is best and updating the docs.

**Comment by bphilly96** [comment]
> I'd be curious to know what @wbthomason thinks, but I personally feel that a lot of people in the nvim community are quite new to lua let alone to lua patterns, by not escaping this/trying to accomodate patterns I feel this makes this feature have quite a high barrier to entry since in order to use it literally i.e. 'please lazy load directly "my-module"' a user would have to understand that they need to escape the pattern.

This is a fair point. For what it's worth I personally haven't needed to use patterns yet, I just noticed the discrepancy between the docs and code when I was working on #292. All of the plugins I use this for have only 1 exact module name I want to lazy load on so maybe keeping it simple is the best.

**Comment by wbthomason** [comment]
So, the intent of using patterns here was to allow e.g. `module = 'plenary*'`, to allow lazy-loading on anything that `plenary` provides without explicitly listing it. The thinking was also that using patterns only generalized the use of literal names - for example, I thought that `-` was only a magic char inside a character class specification (i.e. that `1-5` would match the literal string `1-5`, but `[1-5]` would match any single digit between 1 and 5 inclusive). This was clearly wrong.

I overlooked the effect that `pesc` would have on this when reviewing the PR that added it, and the docs also ought to be updated.

I agree with @akinsho; given the prevalence of certain magic characters in Lua module names and the fact that we already effectively provide support for prefix patterns (which I suspect to be the main/maybe only use of patterns in this feature), we should update the docs to indicate that users provide a literal module name. If there's a request for the more advanced feature in the future, we can revisit allowing patterns.
