### ISSUE TITLE
Unable to install Plugins

### ISSUE THREAD

**Issue by GustavoPrietoP** [wbthomason/packer.nvim#324]
- `nvim --version`: 0.5
- `git --version`: 2.31
- Operating system/version: Arch Linux
- Terminal name/version: Alacritty (but it really doesn't matter)

### Steps to reproduce
```git clone https://github.com/GustavoPrietoP/evil-nvim.git```
### Actual behaviour
Breaks the whole packer plugin.
### Expected behaviour
Install's plugins as normal.

It seems like it's a packer issue. On my computer, it works fine but whenever I try on a VM I get the same issue. I tried everything and can't seem to get it working with packer (i installed paq and it worked perfectly).

Edit: This is my config file

**Comment by akinsho** [comment]
@GustavoPrietoP just so I understand correctly the issue is that when `evil-nvim` is specified as a plugin for packer using `use "evil-nvim"` it breaks, it would be good to know what you mean by breaks. Are there any specific error messages? what is breaking exactly?

Looking at `evil-nvim` is the intent that it should be installed as a plugin because it isn't structured as a (n)vim plugin and more like a configuration file?

When you say it works with `paq` what does that look like? 

Lastly should this be how that configuration is setup i.e. as a packer plugin itself rather than something a user clones? because it will mean that they are constantly having to update the plugin directory which will mean that they won't be able to update config/plugin since it will have local changes

**Comment by wbthomason** [comment]
@GustavoPrietoP I do not see a link to your config file; can you please add it?

**Comment by GustavoPrietoP** [comment]
> @GustavoPrietoP I do not see a link to your config file; can you please add it?

hey, I switched to paq everything seems to work fine now. Sorry for the inconvenience.
this was the issue
![image](https://user-images.githubusercontent.com/70907734/116252086-3e992680-a73d-11eb-97c8-aa34efc59fa8.png)

**Comment by GustavoPrietoP** [comment]
we no longer use packer so there is no way to replicate this anymore (im pretty sure you guys didn't try it either because you would've gotten that error)

here was the commit. You can check all the changes and see if there is anything wrong with how packer was set up
https://github.com/GustavoPrietoP/evil-nvim/commit/56bbc039b7470a04aafbcf67e56b41765e1636e8

**Comment by nanotee** [comment]
Not a `packer` bug

[This is what causes the error message](https://github.com/GustavoPrietoP/evil-nvim/blob/56bbc039b7470a04aafbcf67e56b41765e1636e8/lua/doom-settings.lua#L10)

**Comment by GustavoPrietoP** [comment]
do you know why it works on my machine?

**Comment by nanotee** [comment]
Not sure I understand your question

I believe the issue is that `packer` sets the `filetype` option for its own buffer on line 643 in `display.lua`, which triggers the `FileType *` autocmd before the mark is set (I can't reproduce 100% of the time though).

(Also, be careful not to pad your `vim.cmd` strings. Here the trailing space is interpreted as part of the `:norm` command, so instead of executing `'"` it executes `'"<Space>`)

[defaults.vim](https://github.com/vim/vim/blob/master/runtime/defaults.vim#L107-L110) has a similar autocmd that handles cases where the mark isn't set. I've been using it for a while and I have yet to encounter an issue with it.
