### ISSUE TITLE
Compiling config function do not work with references declered outside of the function

### ISSUE THREAD

**Issue by HOnatToprak** [wbthomason/packer.nvim#334]
When config function use variables or functions declared outside of the function scope yields as nil value on packer_compile.

### Steps to reproduce
For example in use expression below
`use {'neovim/nvim-lspconfig', config=require 'lspconfiguration'.configure}`

lspconfiguration.lua does not work as below
```
local function message()
    vim.cmd 'echom "hello"'
end

local function configure()
    message()
end

return {
	configure = configure,
}
```

But it works as
```
local function configure()
    local function message()
        vim.cmd 'echom "hello"'
    end

    message()
end

return {
	configure = configure,
}
```

### Actual behaviour
On packer compiled, call attempt to nil error.

### Expected behaviour
echom "hello"

**Comment by wbthomason** [comment]
This is a known issue because we rely on Lua's `string.dump` to compile config functions to bytecode, which cannot handle upvalues. It should be resolved soon by some architectural changes, but a mention of this limitation should be added to the docs in the meanwhile (I actually could've sworn we already said this, but I can't find it anywhere).
