### ISSUE TITLE
Applying autocommand prevents plugin from loading

### ISSUE THREAD

**Issue by medwatt** [wbthomason/packer.nvim#357]
I am trying to use the markdown-preview plugin to preview markdown documents and another plugin that provides proper syntax for pandoc's markdown.

```lua
-- Markdown
use {'iamcco/markdown-preview.nvim',
    run = 'cd app && yarn install',
    cmd = 'MarkdownPreview', ft = {'markdown', 'markdown.pandoc'}}
use 'vim-pandoc/vim-pandoc-syntax'
```

To use the syntax plugin, you need to either manually do set the filetype to markdown.pandoc when you open a markdown file or create an autocommand that does that for you. This is how I was using things with VimPlug.

```vim
augroup Markdown
    autocmd!
    autocmd BufNewFile,BufFilePre,BufRead *.md
    \ set filetype=markdown.pandoc
augroup END
```

For some reason, the autocommand prevents the markdown-preview plugin from loading. Removing the autocommand solves the issue, but this forces me to have to manually set the filetype every time I open a markdown file.

**Comment by wbthomason** [comment]
Thanks for the report! Could you please provide your `packer_compiled` file (as requested in the issue template)?

I suspect this is an issue with the order in which your autocommand and `packer`'s fire. Where do you make your filetype setting autocommand?

**Comment by medwatt** [comment]
@wbthomason, here's my [packer_compiled](https://pastebin.com/AY1uVptd) file.

Basically, my init.lua file initially loads all the plugins. Then it loads another file which has all my settings, where I also have the autocommands defined.

**Comment by francisco285** [comment]
@medwatt You can try to use the ++nested flag:
```viml
augroup Markdown
    autocmd!
    autocmd BufNewFile,BufFilePre,BufRead *.md ++nested set filetype=markdown.pandoc
augroup END
```

**Comment by wbthomason** [comment]
Sorry for not getting to this sooner; I am terribly behind on issues for `packer` right now. The `nested` flag may help - if not, I'd suggest looking at `packer`'s `event` lazy-loader - you could load `markdown-preview` on `event = 'BufNewFile,BufFilePre,BufRead *.md'`, and - in the `config` function for `markdown-preview` - setting the filetype so that `pandoc-syntax` loads. I haven't tested this yet, but in theory it should work.

**Comment by medwatt** [comment]
@francisco285, this didn't help.

**Comment by medwatt** [comment]
@wbthomason this also doesn't work. The Markdown Preview doesn't load if I load the autocommand, no matter what I do?

**Comment by medwatt** [comment]
Still no solution to this issue.

**Comment by francisco285** [comment]
@medwatt I think I found out what's going on. The plugin is actually being loaded, it's just that the commands and other stuff are not being set. That happens because markdown-preview will set commands locally to the current buffer, but only if the [filetype is recognized by markdown-preview](https://github.com/iamcco/markdown-preview.nvim/blob/e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143/plugin/mkdp.vim#L121).

You can change `g:mkdp_filetypes` to support `markdown.pandoc`, so the commands will be available when the autocommand is triggered.

`tl;dr`:

```lua
-- Markdown
use {'iamcco/markdown-preview.nvim',
  run = 'cd app && yarn install',
  setup = function()
    vim.g.mkdp_filetypes = {'markdown', 'markdown.pandoc'} -- or change this variable in another file
  end,
  cmd = 'MarkdownPreview', ft = {'markdown', 'markdown.pandoc'}}
use 'vim-pandoc/vim-pandoc-syntax'
```
(and you can leave the autocommand the way it is)

**Comment by medwatt** [comment]
@francisco285, Thanks!! The issue is solved. Can you explain why it is necessary to add `g:mkdp_filetypes` to support `markdown.pandoc` for packer, but not for other plugin managers (like vimplug) ?

**Comment by francisco285** [comment]
I don't use vimplug, so I don't know why it works differently, but for me, it looks like everything is alright with packer.

Your autocommand changes the filetype of markdown files from `markdown` to `markdown.pandoc`, markdown-preview's autocommand is only triggered if the filetype is in `g:mkdp_filetypes`, which is just `['markdown']` by default.

Even though packer is loading the plugin, the plugin file is defining its autocommand, but not triggering it right away.

So the order autocommands are used is probably: packer loads the plugin -> your autocommand is triggered, which changes the filetype -> markdown-preview autocommand doesn't trigger because filetype is not markdown anymore.

Setting `g:mkdp_filetypes` to `['markdown', 'markdown.pandoc']` before `markdown-preview` is loaded makes `markdown-preview` define its autocommand in such a way that it also triggers when the filetype is `markdown.pandoc`, hence making the order those autocommands are triggered not relevant.

In general, it's a good practice to avoid depending on autocommands order when possible, since it can be very confusing sometimes.
