### ISSUE TITLE
Extra trailing white spaces

### ISSUE THREAD

**Issue by ChuckDaniels87** [wbthomason/packer.nvim#359]
- `nvim --version`: v0.5.0-dev+1325-gdab6b08a1
- `git --version`: 2.31.1
- Operating system/version: Arch Linux
- Terminal name/version: Gnome Terminal 40.1

### Steps to reproduce

I have noticed that for some commands there are trailing whitespaces in the header and some lines that provide information.

I have highlight configured for trailing whitespaces so it is very noticeable.

### Actual behaviour

Example using: PackerStatus

![screenshot](https://user-images.githubusercontent.com/8478202/118411457-fb273d80-b694-11eb-8ad5-82239ceeffb5.png)

### Expected behaviour

It would be nice if there were no extra whitespaces.

### Additional Notes

This *bug* is obviously a really minor one. I have recently move my config from Plug to packer.nvim and I am very happy with it overall. Thank you very much for building this awesome project for the community. Great job!

If you are interested, I could give a try and create a patch and open PR.

**Comment by akinsho** [comment]
@ChuckDaniels87 thanks for raising this, I have some similar functionality for this sort of thing in my config and a *long* block list of filetypes with this sort of thing but have also contributed fixes for this sort of thing in the past. I actually hadn't noticed it with packer tbh but not sure if it went in my block list a long time ago.

Tbh a PR would be greatly appreciated since there's quite a lot of work/issues to go around and any help would be fantastic.
