### ISSUE TITLE
Add a manually loaded state for PackerStatus

### ISSUE THREAD

**Issue by kevinhwang91** [wbthomason/packer.nvim#363]
### Describe the feature
For now, opt plugins' loaded state in `PackerStatus` is a boolean value, true or false is decided by whether the plugin is loaded by packer.
I want an intermediate state like `manually loaded` for loading plugin by `packadd`. The code like below should work as I expected.
```diff
+    local rtps = api.nvim_list_runtime_paths()
     for plug_name, plug_conf in pairs(plugins) do
+      local load_state = ''
+      if not plug_conf.loaded then
+        load_state = vim.tbl_contains(rtps, plug_conf.path) and ' (manually loaded)' or ' (not loaded)'
+      end
       local header_lines = {
-        fmt(" • %s", plug_name) .. (not plug_conf.loaded and ' (not loaded)' or '')
+        fmt(" • %s", plug_name) .. load_state

```
A style for syntax highlight or a name of intermediate state I can't decide, so I provide the idea and the code here instead of a PR.

**Comment by kevinhwang91** [comment]
BTW, I expect to list the path as a detailed value, I can `<C-w>gf` to use my file manager to hack the new plugin I try.

**Comment by akinsho** [comment]
@kevinhwang91 thanks for raising this I actually added `PackerStatus` with the aim for future iterations like, being able to load the plugin from the status bar or view latest commits and diff them or uninstall them. Haven't gotten round to any of that yet 😅 . I think this options of checking if it's in the `rtp` is good since it's more reflective of what's true regardless of what packer knows.

I don't think it needs a specific highlight IMO I think over time this panel will get busier and I'm not sure it's relevant enough to warrant highlighting *on top* of the very clear text.

Regarding the filepath if you dig up the original PR it had the full path in but I removed them because initially you couldn't toggle the plugins content and it was way too distracting and repetitive since the path was pretty similar and long. I think now that each plugin can be toggled it's fine/useful to re-add 👍🏾 

All of this is just a long way of saying I think this is a good idea if you want to go ahead and open a PR but I don't think you should highlight the new loaded state

**Comment by kevinhwang91** [comment]
IMO, the code in `lua/packer/display.lua` is more subjective that is full of UI and style, 1 + 1 is less than 2 in that part. And I am tried of deciding which color style is better for most users. Please forgive my laziness :(

**Comment by akinsho** [comment]
> IMO, the code in lua/packer/display.lua is more subjective that is full of UI and style, 1 + 1 is less than 2 in that part.

Not sure I understand tbh but guessing you're not up for implementing in which case maybe someone else will take this up 🤷🏾‍♂️
