### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by siduck76** [wbthomason/packer.nvim#400]
Hi there! I get this issue with PackerInstall and PackerUpdate, 
 
![image](https://user-images.githubusercontent.com/59060246/121628899-c5108a00-ca97-11eb-9f88-cd17d7a19cb3.png)

nvim version :

![image](https://user-images.githubusercontent.com/59060246/121628866-b629d780-ca97-11eb-85cd-0496e60dbbd0.png)

**Comment by wbthomason** [comment]
Thanks for your report! Please see #389 and the notice in the README added in aa8ca30 (basically, your Neovim is probably too old).

**Comment by siduck76** [comment]
I installed neovim from master.zip , I thought it was new :c

**Comment by wbthomason** [comment]
Ah, no worries. Must've been unexpectedly stale. I'm glad things are working now!

**Comment by xeho91** [comment]
I am confused. How can I build the "_latest_" Neovim version _(with the required pull)_, to enable this feature (`noautocmd`)?

I am doing everything as instructed on [Neovim's Wiki](https://github.com/neovim/neovim/wiki/Building-Neovim),
and the version _([the latest commit - 141647c](https://github.com/neovim/neovim/commit/141647cfbb1f137e3eefe6ba8e658b475e902cac))_ I get is:
```
NVIM v0.5.0-dev+1403-g141647cfb
Build type: Debug
LuaJIT 2.1.0-beta3
```

And it doesn't work, because _(from what I understand)_ this is a version behind the required one. I am sure I'm missing some steps in the building, and I need a guidance.

**Comment by siduck76** [comment]
@xeho91 git clone neovim repo 

- make CMAKE_BUILD_TYPE=RelWithDebInfo
- sudo make install
