### ISSUE TITLE
Unable to lazy load nvim-autopairs 

### ISSUE THREAD

**Issue by siduck76** [wbthomason/packer.nvim#448]
I load nvim-compe at InsertEnter event and nvim-autopairs too , I tried loading nvim-autopairs after compe but it gives me this error : 

![image](https://user-images.githubusercontent.com/59060246/124506423-3e767080-dde9-11eb-932a-8d41f5a4e34f.png)

My config : 
![image](https://user-images.githubusercontent.com/59060246/124506401-31598180-dde9-11eb-9557-967b83542784.png)

**Comment by akinsho** [comment]
@siduck76, you probably don't need the `event = "InsertEnter"` as well as the `after = "nvim-compe"`, I could be wrong, but that looks like it will cause a race conditions since if they both load on insert enter then one might beat the other to start. If you have already set `nvim-compe` to load on insert enter, then you should just rely on the after config alone.

So some of this is not really down to packer but the fact that one plugin implicitly depends on the other and isn't documented. You need to load `nvim-autopairs` after `compe` similar to what you have, but your `event` key is what is likely causing this issue. I managed to get this to work locally just using `after` only on `autopairs`
