### ISSUE TITLE
Should I Git Commit packer_compiled

### ISSUE THREAD

**Issue by jrock2004** [wbthomason/packer.nvim#462]
I am not sure if I should commit the packer_compiled.lua file? Could that cause issues between computers? I tried looking but could not find out the answer

**Comment by wbthomason** [comment]
Up to you. It shouldn't cause issues between computers if no part of your setup is dependent on a specific computer (e.g. if you don't have `cond` keys that check for certain environment variables, etc.), but you certainly don't need to commit it. If you regularly run `PackerCompile` or `PackerSync`, you may see some churn in your git repo, because Lua table iteration order isn't stable, and so compile results for the same spec may differ by ordering.

**Comment by gegoune** [comment]
And exactly that (combined with constant juggling with plugins) made me to gitignore it.

**Comment by jrock2004** [comment]
Thank you for this information
