### ISSUE TITLE
LazyLoading by base module path

### ISSUE THREAD

**Issue by thezealousfool** [wbthomason/packer.nvim#478]
Great project. Thanks for all the work you have put into it.

### Describe the feature

The following telescope configuration fails
```lua
	use({
		"nvim-telescope/telescope.nvim",
		requires = {
			{ "nvim-lua/popup.nvim", module = "popup" },
			{ "nvim-lua/plenary.nvim", module = "plenary" },
		},
		module = "telescope.builtin",
		config = function()
			require("plugins/telescope").config()
		end,
		setup = function()
			require("plugins/telescope").mappings()
		end,
	})
```
This is because I have `plenary` lazyload using "module" but the telescope does not require plenary directly instead requires submodules like `plenary.job`, `plenary.log`, `plenary.reload` etc. 

Is there some way that I can lazyload `nvim-lua/plenary.nvim` whenever any of `plenary.*` is required?

**Comment by thezealousfool** [comment]
The example I have given might not be the best example as in the case of dependencies they get lazy loaded along with the parent plugin, but even for telescope I mention `module = "telescope.builtin"` and not `module = "telescope"` as in my keymaps I have used `telescope.builtin`.

**Comment by akinsho** [comment]
Hi @thezealousfool, so this was originally the plan when we implemented and discussed the module feature. The issue we encountered was that it was either or regarding using lua patterns. The string a user passes in the `module` key is passed to `string.match(<my-string>)` the issue that arose was that for the simple use case for any user unfamiliar with lua patterns, names like `cool-plugin` would not work because the pattern would interpret special characters so wouldn't match correctly.

So in order to support the simple use case which I imagine is most common, we pass the exact module name and escape any special characters. So `plugin*` won't work. It's sort of either or, i.e. all users need to know to escape lua patterns to make a simple case work, or we just support that, which is where we landed.

I think down the line packer could maybe allow some sort of option or configuration for this (up to @wbthomason) but my feeling is that packer's complexity is mounting and in the short term I think it would be good to focus on stability rather than new features. FWIW, there are still issues and bugs being dealt with the module feature (e.g. #469). I'd be wary of adding more complexity to it now.

**Comment by thezealousfool** [comment]
@akinsho That makes a lot of sense. Thanks for the clarification. I totally agree with the stability over features.

Feel free to close the issue or keep it open if you think you might come back to it in future.

**Comment by wbthomason** [comment]
I agree with the focus on stability over features - in particular, I really don't want to add significant features before #402. However, I think that this case could be handled without a significant increase in complexity by adding a `module_pattern` key, which is exactly the same as `module` except that we don't do escaping and the user is required to get their pattern syntax right. @akinsho do you think that's a reasonable balance between adding a (small, imo) amount of additional complexity and enabling this use case?

**Comment by akinsho** [comment]
@wbthomason that seems like a simple and good solution. I guess my wariness is just around the growing surface area of packer and how much there is to add tests for and validate continues to work + how easy things are to grok for users (in general) but as for this specific issue this seems like quite a sensible solution that doesn't involve a great deal of complexity.

**Comment by wbthomason** [comment]
Agreed on all points, @akinsho!
