### ISSUE TITLE
'after' config key is not respected

### ISSUE THREAD

**Issue by vatosarmat** [wbthomason/packer.nvim#564]
Hello. I have `vim-rooter` in my plugin spec. I use its `config` function to set global variable `project_type` after it is loaded. This `project_type` is later used to configure `fzf ` commands, e.g. add `CMakeFiles` or `node_modules` to `fd/rg` ignore list. So `fzf` must be loaded after `vim-rooter`. But, as seen from `:scriptnames` output below, `after` key didn't work. What could be the reason?

### Steps to reproduce
```lua
  use { '~/.fzf', as = 'fzf', after = 'vim-rooter' }
  use {
    'junegunn/fzf.vim',
    after = 'fzf',
    config = function()
      vim.cmd('source $STD_PATH_CONFIG/plug-config/fzf.vim')
    end
  }
  use {
    'airblade/vim-rooter',
    config = function() require 'plug-config.project_type' end
  }
```

### Actual behaviour
`scriptnames` output:
```
 38: ~/.fzf/plugin/fzf.vim
 39: ~/.local/share/nvim/site/pack/packer/opt/fzf.vim/plugin/fzf.vim
 40: ~/dotfiles/.config/nvim/plug-config/fzf.vim
 ...
 56: ~/.local/share/nvim/site/pack/packer/start/vim-rooter/plugin/rooter.vim
```

**Comment by akinsho** [comment]
@vatosarmat I believe the root cause of this is a duplicate of #272, the reason this is happening is that vim rooter is not an opt or conditionally loaded plugin so trying to load another plugin `after` it won't work since packer doesn't handle sequencing for start plugins. Anyway, this should be resolved when that is fixed. What you can do in the short term is add `event = 'VimEnter'` to `vim-rooter` in the short term till that is fixed

**Comment by vatosarmat** [comment]
Thank you, this helped
