### ISSUE TITLE
Is there a way to append to compile file

### ISSUE THREAD

**Issue by tami5** [wbthomason/packer.nvim#68]
Hey @wbthomason, is it possible to append pkg config to packer's compiled file only when a new plugin added or a field evaluating to true?. 

I'm currently trying to further decouple my setup (perhaps by adding new fields and a condition: `if opts.pkg_new or opts.reload then ... end` and the result would be to call `packer.compile() `or more preferably call something like `packer.compile('name')` if possible). 

So if you would tell if the above the intent above doable with packer noe , or perhaps achievable with builtin helper function? I would appropriate it a lot.

Thanks and as always, looking forward for future commits.

PS: I like the idea of using packer as a library to manage dependencies. Which would be truly awesome with silent calls

**Comment by wbthomason** [comment]
The short answer is "not really, and I don't think this is likely to be added".

The slightly longer answer is that the compiled file is generated all at once because certain features (like sequential loading, etc.) require knowledge of the full set of specified plugins in order to be correctly generated. Though I am looking at some restructuring of the compilation process (to move some code to the `autoload/` directory and some to `ftplugin`s), incremental generation of the file would mean giving up some of these features.

That said, you can do mostly what you're suggesting using the `cond` feature. `cond` allows you to specify a test to run in order to load a plugin, meaning that you could have a test for your "field evaluating to true" to determine whether or not to load a given plugin. This isn't 100% what you want, because it still installs the plugin, but it would at least help with controlling loading.

Another option is looking at the `disable` keyword, which is a boolean value that determines whether or not a given plugin should even be installed. Specifying this as equal to your desired condition would let you control whether a given plugin is installed or not.

I hope this helps!

**Comment by tami5** [comment]
It helps a lot thanks @wbthomason
