### ISSUE TITLE
PackerCompile throws error "Error running config for telescope.nvim: [string "..."]:0: attempt to index upvalue"

### ISSUE THREAD

**Issue by vignesh0025** [wbthomason/packer.nvim#683]
- `nvim 0.5.1`:
- `git version 2.33.1`:
- `Opensuse Tumbleweed`
- `Alacritty 0.9.0`

### Steps to reproduce
- Define the keymaps and autocmds in external module and export them in global config file
- call the keymaps and autocmds in a function in global config and export the function to packer config
- Import the global config module and pass the function to **use**
- run :PackerCompile

### Actual behaviour
The following error is thrown:
PackerCompile throws error "Error running config for telescope.nvim: [string "..."]:0: attempt to index upvalue"

### Expected behaviour
Compilation should occur without issue

### packer files

<details>
<summary>Config Files are here:</summary>
[https://gist.github.com/vignesh0025/f03e55f9b8d5ec529f082b11ae34b304](https://gist.github.com/vignesh0025/f03e55f9b8d5ec529f082b11ae34b304)
</details>

<details>
<summary>packer log file</summary>
No file is present in the path
</details>

<details>
<summary>packer compiled file</summary>
-- Automatically generated packer.nvim plugin loader code

if vim.api.nvim_call_function('has', {'nvim-0.5'}) ~= 1 then
  vim.api.nvim_command('echohl WarningMsg | echom "Invalid Neovim version for packer.nvim! | echohl None"')
  return
end

vim.api.nvim_command('packadd packer.nvim')

local no_errors, error_msg = pcall(function()

  local time
  local profile_info
  local should_profile = false
  if should_profile then
    local hrtime = vim.loop.hrtime
    profile_info = {}
    time = function(chunk, start)
      if start then
        profile_info[chunk] = hrtime()
      else
        profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
      end
    end
  else
    time = function(chunk, start) end
  end
  
local function save_profiles(threshold)
  local sorted_times = {}
  for chunk_name, time_taken in pairs(profile_info) do
    sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
  end
  table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
  local results = {}
  for i, elem in ipairs(sorted_times) do
    if not threshold or threshold and elem[2] > threshold then
      results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
    end
  end

  _G._packer = _G._packer or {}
  _G._packer.profile_output = results
end

time([[Luarocks path setup]], true)
local package_path_str = "/home/vignesh/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/vignesh/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/vignesh/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/vignesh/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/home/vignesh/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

time([[Luarocks path setup]], false)
time([[try_loadstring definition]], true)
local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    vim.schedule(function()
      vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
    end)
  end
  return result
end

time([[try_loadstring definition]], false)
time([[Defining packer_plugins]], true)
_G.packer_plugins = {
  ColorChange = {
    loaded = true,
    path = "/home/vignesh/.local/share/nvim/site/pack/packer/start/ColorChange",
    url = "/home/vignesh/.config/nvim/plugins/ColorChange"
  },
  ["coc.nvim"] = {
    loaded = true,
    path = "/home/vignesh/.local/share/nvim/site/pack/packer/start/coc.nvim",
    url = "https://github.com/neoclide/coc.nvim"
  },
  ["packer.nvim"] = {
    loaded = true,
    path = "/home/vignesh/.local/share/nvim/site/pack/packer/start/packer.nvim",
    url = "https://github.com/wbthomason/packer.nvim"
  },
  ["plenary.nvim"] = {
    loaded = true,
    path = "/home/vignesh/.local/share/nvim/site/pack/packer/start/plenary.nvim",
    url = "https://github.com/nvim-lua/plenary.nvim"
  },
  ["telescope-fzf-native.nvim"] = {
    loaded = true,
    path = "/home/vignesh/.local/share/nvim/site/pack/packer/start/telescope-fzf-native.nvim",
    url = "https://github.com/nvim-telescope/telescope-fzf-native.nvim"
  },
  ["telescope.nvim"] = {
    config = { "\27LJ\2\n½\2\0\0\t\1\19\0\0276\0\0\0'\2\1\0B\0\2\0029\0\2\0005\2\r\0005\3\t\0005\4\a\0005\5\5\0006\6\0\0'\b\3\0B\6\2\0029\6\4\6=\6\6\5=\5\b\4=\4\n\0035\4\v\0=\4\f\3=\3\14\0025\3\15\0004\4\0\0=\4\16\3=\3\17\2B\0\2\1-\0\0\0009\0\18\0B\0\1\1K\0\1\0\0À\22telescope_keymaps\fpickers\17file_browser\1\0\0\rdefaults\1\0\0\25file_ignore_patterns\1\4\0\0\17node_modules\n%.out\fplugged\rmappings\1\0\1\18prompt_prefix\nð \6i\1\0\0\n<Esc>\1\0\0\nclose\22telescope.actions\nsetup\14telescope\frequire\0" },
    loaded = true,
    path = "/home/vignesh/.local/share/nvim/site/pack/packer/start/telescope.nvim",
    url = "https://github.com/nvim-telescope/telescope.nvim"
  }
}

time([[Defining packer_plugins]], false)
-- Config for: telescope.nvim
time([[Config for telescope.nvim]], true)
try_loadstring("\27LJ\2\n½\2\0\0\t\1\19\0\0276\0\0\0'\2\1\0B\0\2\0029\0\2\0005\2\r\0005\3\t\0005\4\a\0005\5\5\0006\6\0\0'\b\3\0B\6\2\0029\6\4\6=\6\6\5=\5\b\4=\4\n\0035\4\v\0=\4\f\3=\3\14\0025\3\15\0004\4\0\0=\4\16\3=\3\17\2B\0\2\1-\0\0\0009\0\18\0B\0\1\1K\0\1\0\0À\22telescope_keymaps\fpickers\17file_browser\1\0\0\rdefaults\1\0\0\25file_ignore_patterns\1\4\0\0\17node_modules\n%.out\fplugged\rmappings\1\0\1\18prompt_prefix\nð \6i\1\0\0\n<Esc>\1\0\0\nclose\22telescope.actions\nsetup\14telescope\frequire\0", "config", "telescope.nvim")
time([[Config for telescope.nvim]], false)
if should_profile then save_profiles() end

end)

if not no_errors then
  vim.api.nvim_command('echohl ErrorMsg | echom "Error in packer_compiled: '..error_msg..'" | echom "Please check your config for correctness" | echohl None')
end
</details>

**Comment by felixr** [comment]
I ran into the same issue and the reason was that I declared a local variable and referenced it in the config function. eg.

```
local vim = vim
use {'foo/bar', config = function() vim.api.nvim_exec() }
```

`vim` in the config function now does not reference the global variable anymore, but the local vim variable is not defined when the function is executed. So `vim` will be `nil` and `vim.api` will `attempt to index upvalue`.

In your example you probably have the same issue with `global_config.telescope_init`. Try ` config =  function() require('global_config').telescope_init() end`

**Comment by vignesh0025** [comment]
That solved the my issue. Thank you @felixr

**Comment by wbthomason** [comment]
Yes, this is a known shortcoming of the `string.dump`-based compilation approach. Once this is removed in #402, the restriction will also be removed.

**Comment by vedattt** [comment]
**Leaving my solution to this problem for anyone of interest:**

In my case, I have a directory structure where each plugin's configurer function is contained in its own file. The files return a module with a `configure` function, which I wanted to pass to packer's `config` option:

```lua
use {
  -- ...
  config = require("plugins.some_plugin_module").configure
}
```

The problem is that the configurer functions may freely use any other function/variable within their respective plugin files. As mentioned, this does not work with the current compilation approach because those function/variables used aren't included in packer's compiled output, hence the error.

The solution is simple, pass a function to packer's `config` option that then `require`s the plugin's configurer function and calls it. Since the `require` statement will be in packer's compiled output, this works. At runtime, the `require` will behave as it typically does:

```lua
use {
  -- ...
  config = function() require("plugins.some_plugin_module").configure() end
}
```

However, this can get messy and repetitive as you type up more and more of the `config` functions above.
So, let's define a function that will return the function above, with an argument to pass the plugin module's name:

```lua
local function get_configurer(config_name)
  return function() require("plugins." .. config_name).configure() end
end

-- Use as such
use {
  -- ...
  config = get_configurer("some_plugin_module")
}
```
**Except, this won't work.** Once again, the function compiled by packer is referencing a variable that is not included in the compiled output: `config_name`.

Now, here is the workaround. We simply need to find a way to cheat the `config_name` into the function compiled by packer. We achieve that by compiling the configurer function ourselves, through `loadstring`:

```lua
local function get_configurer(config_name)
  return loadstring("require('plugins." .. config_name .. "').configure()")
end
```

And with that:
- We are free to do whatever in our per-plugin configurer functions
- We can have a generic function to set the `config` options with
- The compiled packer output isn't concerned with missing "out-of-scope" code

**Comment by EdenEast** [comment]
Another solution is to create your own custom handler using `set_handler`.

```lua
packer.set_handler("conf", function(_, plugin, value)
  plugin.config = ([[require('plugins.%s').configure()]]):format(value)
end)

-- ...

use({
  "user/repo",
  conf = "module_name",
})
```
