### ISSUE TITLE
How do you lazy load a plugin on require?

### ISSUE THREAD

**Issue by medwatt** [wbthomason/packer.nvim#685]
I have been able to lazy load most of my plugins, but I can't seem to be able to lazy load those that use the `require` keyword.

For example, I have the module given below that I'd like to be loaded when I call `
lua require('spectre').open()`. I have tried using the `fn`, `cmd`, and `module` options, but the module doesn't get loaded. Any ideas would be appreciated.

```lua
use {'windwp/nvim-spectre',
    module = 'nvim-spectre'
}
```

**Comment by akinsho** [comment]
@medwatt module should work (I have a few of those in my config) In your example, though you aren't referring to spectre by the name of the module. The module you are requiring is `require('spectre')` but you have specified the plugin name in the module key not the name of the lua module you are requiring, which is why this doesn't work

**Comment by medwatt** [comment]
> @medwatt module should work (I have a few of those in my config) In your example, though you aren't referring to spectre by the name of the module. The module you are requiring is `require('spectre')` but you have specified the plugin name in the module key not the name of the lua module you are requiring, which is why this doesn't work

Thanks! Rookie mistake.

**Comment by medwatt** [comment]
@akinsho, if you don't mind one more question, how do you lazy load a colorscheme?

**Comment by babygau** [comment]
@medwatt `VimEnter` event should work.
