### ISSUE TITLE
What is the meaning of `W18: Invalid character in group name`?

### ISSUE THREAD

**Issue by zeitchef** [wbthomason/packer.nvim#731]
I'm not able to find any documentation on this error, so before I just give up using it, can someone please explain what this error is?

**Comment by akinsho** [comment]
@zeitchef you can find the matching help tag for any vim error (granted the dev team haven't missed it) by running `:help <ERR_CODE>` in your case `:help W18` it shows that error appears to be with a highlight group name. Potentially a plugin or your config is somehow defining an invalid hl group name and packer is just where this is surfacing since other people aren't seeing this it seems likely related to your config.

**Comment by zeitchef** [comment]
@akinsho Thank you, that's incredibly helpful.

**Comment by TornaxO7** [comment]
Is it possible to get a more detailed error message like *where* this error appears?

**Comment by glyh** [comment]
The same, I want to debug this but it didn't even show where's the error come from.

**Comment by huypl53** [comment]
Latest neovim helped me with this
