### ISSUE TITLE
Feature request: show hunk diff

### ISSUE THREAD

**Issue by ghost** [wbthomason/packer.nvim#78]
Hi Will, please add ability to see diff of each commit from update result window. `vim-plug` has that as well as `:PlugDiff` which can show results of last `:PlugUpdate` command once again.

Great plugin, thanks a lot!

**Comment by wbthomason** [comment]
@katsika, I'd be happy to merge a PR implementing this, but it's not likely to be added soon otherwise.

If you're interested, I can help point you toward the relevant parts of the code.

**Comment by akinsho** [comment]
@wbthomason I *might* be able to look into this in the coming weeks, any pointers on where to start. I've also been missing this feature from plug as I like to look through the code that changed in my plugins from time to time.

**Comment by wbthomason** [comment]
This should be a matter of:
1. Add a function to the plugin table in `lua/packer/plugin_types/git.lua` to run a diff command (you should be good with the existing `config.git.subcommands.diff`/`config.git.subcommands.diff_fmt`, but may also need to add a new subcommand if you want a different diff display format). `plugin.revert_last` in that file should be a good example of a similar function. This function should return a table of lines corresponding to the diff.
2. Add a function in `lua/packer/display.lua` to toggle displaying the diff. `show_all_info` and `toggle_info` in that file should help.
3. Register a keybinding in `display.lua` to display/hide the diff in the display window.

I'm happy to answer any questions you (or anyone else) has along the way! Thanks!

**Comment by akinsho** [comment]
@wbthomason (heads up) for this I was envisioning actually showing the diff not just the commit descriptions which the current diff commands show, the similar functionality from `vim-plug` is [here](https://github.com/junegunn/vim-plug/blob/8b45742540f92ba902c97ad1d3d8862ba3305438/plug.vim#L2601).

It would be much easier to do this by opening a split for the diff but will involve a bigger change to allow the existing display to open a preview with the filetype set to git to get proper syntax highlighting and also as the diff might be quite large I don't think it could easily be added to the current info layout.

**Comment by akinsho** [comment]
@wbthomason I'm a little stuck trying to get my head around how the `async/await` functionality works with `jobs` I essentially am looking to create a `diff` function that returns the lines. I'm able to get the job working but I'm not sure how I return a table value whilst using the async functionality in packer. I've tried using `map_ok` to return values, returning the async function itself etc.

```lua
  plugin.diff = function()
    local r = result.ok(true)
    async(function ()
      local diff_cmd = vim.split("git diff HEAD~ HEAD",'%s+')
      local diff_info = {err = {}, output = {}, messages = {}}
      local diff_onread = jobs.logging_callback(diff_info.err, diff_info.messages)
      local diff_callbacks = {stdout = diff_onread, stderr = diff_onread}
      r = r:and_then(await, jobs.run(diff_cmd, { capture_output = diff_callbacks }))
      print("diff_info: " .. vim.inspect(diff_info))
      return r
    end)()
    return r
  end

```

**Comment by wbthomason** [comment]
> for this I was envisioning actually showing the diff not just the commit descriptions which the current diff commands show, the similar functionality from vim-plug is here

Ah, sorry - I never used that feature when I used `vim-plug`, so I misunderstood what you meant.

> It would be much easier to do this by opening a split for the diff but will involve a bigger change to allow the existing display to open a preview with the filetype set to git to get proper syntax highlighting and also as the diff might be quite large I don't think it could easily be added to the current info layout.

Maybe a floating window would be a good solution? Pop-up diffs?

> I'm a little stuck trying to get my head around how the async/await functionality works with jobs

Yeah, the `async` stuff can be a bit unintuitive at first (though imho it makes writing code that runs a sequence of jobs much easier once you overcome the initial stumbling block).

It is generally easiest to do everything inside the `async` wrapper if anything needs to be `async`. Because of a limitation in how you can use Lua's `coroutine.yield` across C functions, you typically cannot `await` at the top level of a function. The alternative is to provide a callback to your async call, i.e. `async(function() do the diff...end)(function(diff) callback...end)`.

Alternatively, if you don't care if the function blocks, you could just use `system` or similar to circumvent the `async` machinery entirely.

**Comment by akinsho** [comment]
Thanks @wbthomason makes sense now, I kept trying to see if there was a way to `await` the `diff` function but that just caused errors. A callback or just using system makes sense just wanted to make sure I wasn't just missing some obvious thing that would allow me to get the result back some other way.

Re. the floating window tbh I think that's likely to just be fiddly. Since a preview window is a sort of singleton it's easier to work with since I don't have to keep track of window ids and close floats or anything like that, I can just toggle the preview. 

Secondly I think a float would just obscure the rest of the view port and be harder tor resize if necessary. It'd be much more useful for the people who do actually use this functionality to be able to go to and from the packer plugin pane and toggle diffs for different plugins. I guess this will be a bit tough for anyone using a float for packer's display but that's a general problem with floats not specific to this

**Comment by wbthomason** [comment]
Yeah, I wish you could just `await` at the top level, but I haven't found a way to enable it. Making the `async` the top level is close enough for my uses, since I can just wrap the entire function body in `async`.

Preview window sounds good to me - I have much less experience with them, but I buy your argument in their favor.

Thanks!
