### ISSUE TITLE
Weirdly, the first time I install, it saved to ~/.local/share/nvim/site/pac/

### ISSUE THREAD

**Issue by tjdevries** [wbthomason/packer.nvim#9]
It was weird... for some reason it saved to `pac` not to `pack`.

After I moved it, everything was good. So I've got no idea why that happened.

**Comment by wbthomason** [comment]
You mean when you first cloned the repo or ran `packer.install()`? If the latter...that's bizarre. Installing new plugins after the fact hasn't repeated the issue?

**Comment by wbthomason** [comment]
It's possible that the code I had in place to remove the trailing slash from the package root could've caused this if the package root path didn't *have* a trailing slash (though, since it's processed with `fnamemodify(path, ':p')` just beforehand, I'm not sure how that's possible). I've replaced this with something more intelligent that should prevent incorrect truncations; hopefully that fixes the issue?

**Comment by tjdevries** [comment]
Well I fixed it myself manually by just changing the directory and it worked... which was weird. Figured I'd let you know even though I got it running. I was very confused as well.

**Comment by tjdevries** [comment]
Can probably close though -- since it's working for me now (even before that commit)
