### ISSUE TITLE
 invalid value  (boolean) at index 62 in table for 'concat'

### ISSUE THREAD

**Issue by winkee01** [wbthomason/packer.nvim#908]
executing `:PackerSync` causes error: 
[packer.nvim] [ERROR 16:41:57] async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:706: invalid value
 (boolean) at index 62 in table for 'concat'

<img width="1292" alt="CleanShot 2022-05-09 at 16 42 05@2x" src="https://user-images.githubusercontent.com/49930785/167373226-1b3fb09a-53b7-4a65-b8e9-a5fa382efe86.png">

**Comment by Diullei** [comment]
@winkee01 since you didn't post your packer config, I'm not sure if your problem is the same as I had, but anyway I'll share what worked for me...

I had a similar error when trying to load configuration from one of my packages. I was doing something like:

```lua
  use {'projekt0n/github-nvim-theme', config = require("plugins.configs.theme")}
```

After changing to the code below, it worked again:

```lua
  use {'projekt0n/github-nvim-theme', config = function()
      require("plugins.configs.theme")
  end}
```

As I saw in the documentation the `config` property expects a string or a function object and if you pass something different you will see an exception similar to the one you posted.

I hope it helps ;)

**Comment by craigmac** [comment]
@Diullei thanks that worked. Strange thing is, looking through the docs several times `config = { ... }` is used, or an outright `config = { profile = { enable = true, threshold = 1 } }` which would lead us to think that it takes a table, must be some kind of metatable magic happening 😕

**Comment by winkee01** [comment]
Hi thanks, @Duillei has pointed out the correct solution, you can't pass `require()`'s result to the `config` variable because `config` expects a string/table/funtion, but `require()` will return a `boolean` value. I have solved this issue by printing out plugins structure from `packer.nvim/lua/packer.lua`, just forgot to close the issue.

![image](https://user-images.githubusercontent.com/49930785/194683106-80f63dbe-aa08-4393-bfaa-74b25d0ef82c.png)
