### ISSUE TITLE
I've simply change the compile_path and some lazyloading plugins just dont work like before

### ISSUE THREAD

**Issue by NEX-S** [wbthomason/packer.nvim#936]
my packer.lua
```
packer.init {
    auto_clean = true,
    compile_on_sync = true,
    git = { clone_timeout = 6000 },
    compile_path = '~/.local/nvim/compile/packer_compiled.lua',
    display = {
        working_sym = "",
        error_sym = "✗",
        done_sym = "",
        removed_sym = "-",
        moved_sym = "",
        open_fn = function()
            return require("packer.util").float { border = "single" }
        end,
    },
}
```
maybe i should change my runtimepath? Is the any ways to fix this problem?

**Comment by pravuX** [comment]
I have the same issue and frankly don't know where to start looking. It even fails to install nvim-tresitter.

**Comment by EdenEast** [comment]
You need to update your runtimepath in order for nvim to find the compiled file. See `:help rtp` for detailed information on how neovim finds files to load and `require`. For example I do this:

```lua
local home = os.getenv 'HOME'
local cache = home .. '/.cache/nvim'
vim.opt.runtimepath:prepend(cache)

local packer = require 'packer'
packer.init {
  compile_path = cache .. '/plugin/packer_compiled.lua',
}
```

**Note:** I have the compiled file under `plugin`. Since `~/.cache/nvim` is in my runtimepath it will load any `.vim` or `.lua` file found in under the `plugin` folder. (Again check the help docs on how vim/neovim loads files)
