### ISSUE TITLE
vim.schedule error on PackerSync

### ISSUE THREAD

**Issue by kflak** [wbthomason/packer.nvim#96]
Hi, 

Getting this after running PackerSync:
```
[packer] Finished compiling lazy-loaders!
Error executing vim.schedule lua callback: .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:48: bad argument #1 to 'max' (number expected, got no value)
```
Nvim version: 
```
NVIM v0.5.0-852-g3c2402e5c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kf/.cache/yay/neovim-git/src/build/config -I/home/kf/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/kf/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/kf/.cache/yay/neovim-git/src/build/include
Compiled by kf@t480s

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
Arch Linux.

It started happening a couple of days ago.

**Comment by wbthomason** [comment]
Interesting, that part of `packer` hasn't changed since 2020-06-15 (for the function where the error happens)/2020-07-11 (for the function called to produce the argument that seems to cause the error), and I'm also not able to reproduce the error on my end (with a slightly newer Neovim - could you try rebuilding?)

What commit of `packer` are you on? Anything after July should be new "enough" for this not to be buggy. If anything, I'd suspect an upstream error with a change to `vim.fn.getftime`, but that seems unlikely given that everything works for me (also on Arch).

**Comment by kflak** [comment]
OK, found it! Turns out I had `luajit-2.1-git` installed instead of the community repo version of luajit, which is currently on 2.0.5-3, so I suspect there are some changes coming up that you might want to look into...

**Comment by wbthomason** [comment]
Ah, brilliant! Thanks for the heads-up; I'm guessing this will cause upstream breakage too.

**Comment by kflak** [comment]
Happy to help ;-)
